sudo: false
language: cpp
compiler:
  - clang
  - gcc

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  
before_script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./plang_unit
  
script: 
  - $CXX --version

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
